// export const SELECT_COFFEE_TYPE = 'SELECT_COFFEE_TYPE';
// export const COFFEE_TYPE_SELECTED = 'COFFEE_TYPE_SELECTED';
// export const COFFEE_ORDER_SUCCESS = 'COFFEE_ORDER_SUCCESS';
// export const COFFEE_ORDER_FAILED = 'COFFEE_ORDER_FAILED';

